### PR TITLE
feat: adds finalize proposal function

### PR DESCRIPTION
**Pull request by R-K-H**
Wanted a spot check if this is how we were going to do this / where this should be located etc. Thanks!

### CODE REVIEW

**Comment by R-K-H** [comment]
Tagging: https://github.com/metaDAOproject/futarchy-ts/issues/8 for reference.

**Comment by swaggymarie** [comment]
so, I should take this one and test it for various versions ? @R-K-H

**Comment by R-K-H** [comment]
Yes plz. Well v0.2 and v1.0

**Comment by R-K-H** [comment]
Handled in #83

**Pull request closed without merging**
